# Generated by Django 3.0.7 on 2020-07-03 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_User',
            fields=[
                ('USER_PROFILE_NUMBER', models.IntegerField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=20)),
                ('USER_PHONE_NUMBER', models.CharField(max_length=10)),
                ('USER_EMAIL', models.EmailField(max_length=254)),
                ('USER_DESCRIPTION', models.CharField(max_length=1000)),
                ('USER_MOTIVATION_LINE', models.CharField(max_length=150)),
                ('USER_PROFILE_IMAGE', models.ImageField(upload_to='USER_UPLOADS')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Breakfast')),
                ('FOOD', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=100)),
                ('PROTIEN', models.IntegerField()),
                ('CARBOHYDRATE', models.IntegerField()),
                ('FATS', models.IntegerField()),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='USER_Images')),
                ('CAPTION_IMAGE', models.CharField(blank=True, max_length=50)),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Lunch')),
                ('FOOD', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=100)),
                ('PROTIEN', models.IntegerField()),
                ('CARBOHYDRATE', models.IntegerField()),
                ('FATS', models.IntegerField()),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Exercise')),
                ('EXERCISE_NAME', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=50)),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_NAME', models.CharField(max_length=20)),
                ('EVENT_DATE', models.DateField()),
                ('EVENT_START_TIME', models.TimeField()),
                ('EVENT_END_TIME', models.TimeField()),
                ('EVENT_DESCRIPTION', models.CharField(max_length=250)),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Dinner')),
                ('FOOD', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=100)),
                ('PROTIEN', models.IntegerField()),
                ('CARBOHYDRATE', models.IntegerField()),
                ('FATS', models.IntegerField()),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
            ],
        ),
        migrations.CreateModel(
            name='DIET_PLAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABOUT_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.About_User')),
                ('BREAKFAST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Breakfast')),
                ('DINNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Dinner')),
                ('LUNCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Lunch')),
            ],
        ),
    ]
